apiVersion: apps/v1
kind: Deployment
metadata:
  name: goatandwolf
  labels:
    app: goatandwolf
spec:
  selector:
    matchLabels:
      app: goatandwolf
  replicas: 1
  template:
    metadata:
      labels:
        app: goatandwolf
    spec:
      containers:
      - name: goatandwolf
        image: webgoat/goatandwolf:v8.2.2
        ports:
        - containerPort: 9090
        - containerPort: 8080
        env:
        - name: TZ
          value: America/New_York
